### ISSUE TITLE
AttributeError: 'ScaffoldPackage' object has no attribute 'deepcopy'

### ISSUE THREAD

**Issue by mahyar-osn** [ABI-Software/scaffoldmaker#95]
Bug report: 

Seems like there is a bug associated with the ScaffoldPackage copy function in the meshgenerator file when trying the pig and mouse colons.

`Traceback (most recent call last):
  File "d:\sparc\codes\mapclient_plugins\mapclientplugins.meshgeneratorstep\mapclientplugins\meshgeneratorstep\view\meshgeneratorwidget.py", line 314, in _parameterSetChanged
    self._generator_model.setParameterSetName(parameterSetName)
  File "d:\sparc\codes\mapclient_plugins\mapclientplugins.meshgeneratorstep\mapclientplugins\meshgeneratorstep\model\meshgeneratormodel.py", line 443, in setParameterSetName
    self._scaffoldPackages[-1].deepcopy(sourceScaffoldPackage)
AttributeError: 'ScaffoldPackage' object has no attribute 'deepcopy'`

**Comment by mahyar-osn** [comment]
Update: The issue wasn't a bug. Mapclient-meshgeneratorstep must have been updated to comply with the new changes of Scaffoldmaker. This is now resolved.
